// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvhS6YvDOgTe3NtpwYHYBw-3l99o2P9k',
    appId: '1:739170127010:web:7406a8eab32314ecdd5bfb',
    messagingSenderId: '739170127010',
    projectId: 'shroomcard-7a698',
    authDomain: 'shroomcard-7a698.firebaseapp.com',
    storageBucket: 'shroomcard-7a698.firebasestorage.app',
    measurementId: 'G-9GDB9HHF0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA15NqanRfCj0LWApsefKvBeAg-rZ8MpR4',
    appId: '1:739170127010:android:e3eb8ca426e3ce57dd5bfb',
    messagingSenderId: '739170127010',
    projectId: 'shroomcard-7a698',
    storageBucket: 'shroomcard-7a698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6GUi52RE3N2KXbGG4tk28ZRHqeiW6kE',
    appId: '1:739170127010:ios:460df345fc1af161dd5bfb',
    messagingSenderId: '739170127010',
    projectId: 'shroomcard-7a698',
    storageBucket: 'shroomcard-7a698.firebasestorage.app',
    iosBundleId: 'com.example.shroomCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy6GUi52RE3N2KXbGG4tk28ZRHqeiW6kE',
    appId: '1:739170127010:ios:460df345fc1af161dd5bfb',
    messagingSenderId: '739170127010',
    projectId: 'shroomcard-7a698',
    storageBucket: 'shroomcard-7a698.firebasestorage.app',
    iosBundleId: 'com.example.shroomCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuvhS6YvDOgTe3NtpwYHYBw-3l99o2P9k',
    appId: '1:739170127010:web:de3bfbbfa99a9932dd5bfb',
    messagingSenderId: '739170127010',
    projectId: 'shroomcard-7a698',
    authDomain: 'shroomcard-7a698.firebaseapp.com',
    storageBucket: 'shroomcard-7a698.firebasestorage.app',
    measurementId: 'G-RWGHET12LB',
  );
}
